export default {
	"login": "marcysutton",
	"id": 1045233,
	"node_id": "MDQ6VXNlcjEwNDUyMzM=",
	"avatar_url": "https://avatars.githubusercontent.com/u/1045233?v=4",
	"gravatar_id": "",
	"url": "https://api.github.com/users/marcysutton",
	"html_url": "https://github.com/marcysutton",
	"followers_url": "https://api.github.com/users/marcysutton/followers",
	"following_url": "https://api.github.com/users/marcysutton/following{/other_user}",
	"gists_url": "https://api.github.com/users/marcysutton/gists{/gist_id}",
	"starred_url": "https://api.github.com/users/marcysutton/starred{/owner}{/repo}",
	"subscriptions_url": "https://api.github.com/users/marcysutton/subscriptions",
	"organizations_url": "https://api.github.com/users/marcysutton/orgs",
	"repos_url": "https://api.github.com/users/marcysutton/repos",
	"events_url": "https://api.github.com/users/marcysutton/events{/privacy}",
	"received_events_url": "https://api.github.com/users/marcysutton/received_events",
	"type": "User",
	"site_admin": false,
	"name": "Marcy Sutton",
	"company": null,
	"blog": "https://marcysutton.com",
	"location": null,
	"email": null,
	"hireable": null,
	"bio": "Freelance web developer, accessibility advocate, public speaker. Mountain explorer, music junkie, pet lover",
	"twitter_username": "marcysutton",
	"public_repos": 164,
	"public_gists": 26,
	"followers": 1410,
	"following": 65,
	"created_at": "2011-09-12T18:29:27Z",
	"updated_at": "2021-05-25T22:01:49Z"
};
